#!/usr/bin/python3
"""
Run arbitrary C code from a command line.

Note: This is not an actual REPL.
"""

from argparse import ArgumentParser
import os
from pathlib import Path
from shutil import which
import subprocess
import sys
from tempfile import TemporaryDirectory

CC = os.environ.get("CC") or which("cc") or which("gcc") or which("clang")

parser = ArgumentParser(description=__doc__)
parser.add_argument('-m', '--main', action='store_true', help="Wrap code in a main function")

if __name__ == '__main__':
    main = parser.parse_args().main
    with TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)
        script = tmpdir / 'script.c'
        target = tmpdir / 'script'

        with open(script, 'w') as script_file:
            if main:
                script_file.write("int main() {\n")
            script_file.write(sys.stdin.read())
            if main:
                script_file.write("}\n")

        compiler_call = subprocess.call([CC, script, "-o", target])

        process_call = subprocess.call([target])

    exit(process_call)
